import PDFDocument from 'pdfkit';

export const generateInvoicePDF = (invoice, customer, res) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    // Set Response Headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Invoice-${invoice.invoiceNumber}.pdf`);

    // Stream the PDF to the response
    doc.pipe(res);

    // Business Header
    doc
        .fillColor("#444444")
        .fontSize(25)
        .text("InventPro", 50, 50, { align: "left" })
        .fontSize(10)
        .text("Intelligent Inventory Management", 50, 80, { align: "left" })
        .fillColor("#000000")
        .fontSize(10)
        .text("Address Line 1, City", 200, 50, { align: "right" })
        .text("State, Zip Code", 200, 65, { align: "right" })
        .text("Email: billing@inventpro.com", 200, 80, { align: "right" })
        .moveDown();

    // Line separator
    doc.strokeColor("#eeeeee").lineWidth(1).moveTo(50, 110).lineTo(550, 110).stroke();

    // Invoice Meta
    doc
        .fontSize(20)
        .text("INVOICE", 50, 130)
        .fontSize(10)
        .text(`Invoice Number: ${invoice.invoiceNumber}`, 50, 160)
        .text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, 50, 175)
        .text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 50, 190)
        .text(`Status: ${invoice.status.toUpperCase()}`, 50, 205);

    // Customer Info
    doc
        .fontSize(12)
        .text("Bill To:", 350, 130)
        .fontSize(10)
        .text(customer.name, 350, 150)
        .text(customer.email, 350, 165)
        .text(customer.address || "No Address Provided", 350, 180);

    // Table Header
    const tableTop = 250;
    doc
        .fontSize(10)
        .text("Description", 50, tableTop, { bold: true })
        .text("Quantity", 250, tableTop, { align: "center", bold: true })
        .text("Unit Price", 350, tableTop, { align: "center", bold: true })
        .text("Total", 450, tableTop, { align: "right", bold: true });

    doc.strokeColor("#000000").lineWidth(1).moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();

    // Table Content
    let position = tableTop + 30;
    invoice.items.forEach((item, index) => {
        doc
            .fontSize(10)
            .text(item.description, 50, position)
            .text(item.quantity.toString(), 250, position, { align: "center" })
            .text(`$${item.unitPrice.toFixed(2)}`, 350, position, { align: "center" })
            .text(`$${item.total.toFixed(2)}`, 450, position, { align: "right" });

        position += 20;
    });

    // Totals
    const totalsTop = position + 30;
    doc
        .strokeColor("#eeeeee").lineWidth(1).moveTo(300, totalsTop).lineTo(550, totalsTop).stroke()
        .fontSize(10)
        .text("Subtotal:", 350, totalsTop + 10)
        .text(`$${invoice.subtotal.toFixed(2)}`, 450, totalsTop + 10, { align: "right" })
        .text("Tax (18%):", 350, totalsTop + 25)
        .text(`$${invoice.taxAmount.toFixed(2)}`, 450, totalsTop + 25, { align: "right" })
        .fontSize(14)
        .fillColor("#4f46e5")
        .text("Total Amount:", 350, totalsTop + 45, { bold: true })
        .text(`$${invoice.total.toFixed(2)}`, 450, totalsTop + 45, { align: "right", bold: true });

    // Footer
    doc
        .fillColor("#999999")
        .fontSize(8)
        .text("Thank you for your business! If you have any questions, please contact us.", 50, 750, { align: "center" })
        .text("Generated by InventPro Billing Intelligence.", 50, 765, { align: "center" });

    // Finalize the PDF
    doc.end();
};
